# GolangCI-Lint configuration
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - goimports
    - gosec
    - unparam
    - unconvert
    - dupl
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unused
    
    # Ignore shadowing of err
    - linters:
        - govet
      text: 'shadow: declaration of "err"'
    
    # Ignore long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    
    # Ignore weak random in simulator and seed (not security-critical)
    - path: (cmd/simulator|cmd/seed)/main\.go
      linters:
        - gosec
      text: "G404"
    
    # Ignore exitAfterDefer warnings (intended behavior for fatal errors)
    - linters:
        - gocritic
      text: "exitAfterDefer"
    
    # Ignore dupl for decorators (similar code by design)
    - path: internal/shared/repository/decorators/
      linters:
        - dupl
    
    # Ignore dupl for factory (similar code by design)
    - path: internal/factory/repository_factory\.go
      linters:
        - dupl
    
    # Ignore unused functions in service layer (may be used by future features)
    - path: internal/leaderboard/service/
      linters:
        - unused
    
    # Ignore unused types/functions in decorators (part of framework)
    - path: internal/shared/repository/decorators/
      linters:
        - unused
    
    # Ignore unused in websocket hub (debug/future features)
    - path: internal/websocket/hub\.go
      linters:
        - unused

